apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: darkknight97/nodejs-app
    newName: darkknight97/nodejs-app
    newTag: latest
patches:
  - target:
      kind: Deployment
      name: node-app
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
resources:
  - ../base
